name: causal
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.16
  - readline=8.2
  - sqlite=3.41.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==1.3.0
      - anomalib==0.5.0.dev0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==22.2.0
      - autodict==2.0.0
      - av==10.0.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - einops==0.6.0
      - eq==0.0.10
      - filelock==3.10.0
      - fonttools==4.39.2
      - freia==0.2
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - huggingface-hub==0.13.3
      - idna==3.4
      - imageio==2.26.1
      - imgaug==0.4.0
      - importlib-resources==5.12.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonargparse==4.20.0
      - kiwisolver==1.4.4
      - kornia==0.6.9
      - lazy-loader==0.2
      - lightning-utilities==0.8.0
      - littleutils==0.2.2
      - markupsafe==2.1.2
      - matplotlib==3.5.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - networkx==3.0
      - numpy==1.24.2
      - ogb==1.3.5
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.7.0.72
      - outdated==0.2.2
      - packaging==23.0
      - pandas==1.5.3
      - pathtools==0.1.2
      - pillow==9.4.0
      - protobuf==4.22.1
      - psutil==5.9.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytorch-lightning==1.9.4
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qudida==0.0.4
      - requests==2.28.2
      - scikit-image==0.19.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - setuptools==67.6.0
      - setuptools-scm==7.1.0
      - shapely==2.0.1
      - six==1.16.0
      - smmap==5.0.0
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - tifffile==2023.3.21
      - timm==0.6.12
      - tomli==2.0.1
      - torch==2.0.0
      - torchmetrics==0.10.3
      - torchvision==0.15.1
      - tqdm==4.65.0
      - typeshed-client==2.2.0
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - wandb==0.14.0
      - wilds==2.0.0
      - yarl==1.8.2
      - zipp==3.15.0
